//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStoreEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int AdminId { get; set; }
        public string AdminName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public bool IsActivated { get; set; }
        public int LoginTimes { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public int CreatedById { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public int UpdatedById { get; set; }
        public string UpdatedByName { get; set; }
        public int Sequence { get; set; }
    
        public virtual AdminRole AdminRole { get; set; }
    }
}
