//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStoreEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int PermissionId { get; set; }
        public string PermissionName { get; set; }
        public int PermissionCategoryId { get; set; }
        public int Sequence { get; set; }
    
        public virtual PermissionCategory PermissionCategory { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
