//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStoreEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderStatu
    {
        public SalesOrderStatu()
        {
            this.SalesOrders = new HashSet<SalesOrder>();
        }
    
        public int SalesOrderStatusId { get; set; }
        public string SalesOrderStatusName { get; set; }
        public bool IsActivated { get; set; }
        public int Sequence { get; set; }
    
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
    }
}
