//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStoreEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopMenu
    {
        public TopMenu()
        {
            this.MenuCategories = new HashSet<MenuCategory>();
        }
    
        public int TopMenuId { get; set; }
        public string TopMenuName { get; set; }
        public string ToolTip { get; set; }
        public string PageLink { get; set; }
        public int Sequence { get; set; }
    
        public virtual ICollection<MenuCategory> MenuCategories { get; set; }
    }
}
