//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStoreEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PageBinding
    {
        public int PageBindingId { get; set; }
        public string PageTitle { get; set; }
        public int MenuCategoryId { get; set; }
        public string MenuCategoryName { get; set; }
        public int ListMenuId { get; set; }
        public string ListMenuName { get; set; }
        public int AddMenuId { get; set; }
        public string AddMenuName { get; set; }
    }
}
